// Luxury Products - LuxeSense AI
// Each brand has 5-6 products, single color, one size

const PLACEHOLDER = 'https://via.placeholder.com/400x400.png?text=LuxeSense';

export const products = [
  // ============ HERMÈS (6 products) ============
  {
    id: 1,
    name: 'Birkin 25',
    brand: 'HERMÈS',
    category: 'bags',
    price: 11400,
    color: 'Orange',
    inStock: true,
    description: 'The legendary Birkin bag in Togo calfskin with gold hardware.',
    image: require('../images/Hermes/birkin.webp'),
  },
  {
    id: 2,
    name: 'Kelly 28 Sellier',
    brand: 'HERMÈS',
    category: 'bags',
    price: 12100,
    color: 'Noir',
    inStock: true,
    description: 'The iconic Kelly in Epsom calfskin with palladium hardware.',
    image: require('../images/Hermes/kelly.webp'),
  },
  {
    id: 3,
    name: 'Picotin Lock 18',
    brand: 'HERMÈS',
    category: 'bags',
    price: 3350,
    color: 'Gold',
    inStock: true,
    description: 'The playful Picotin Lock in Clemence leather.',
    image: require('../images/Hermes/picotin.webp'),
  },
  {
    id: 4,
    name: 'Constance 24',
    brand: 'HERMÈS',
    category: 'bags',
    price: 13500,
    color: 'Noir',
    inStock: true,
    description: 'The sleek Constance with signature H clasp.',
    image: require('../images/Hermes/constance.webp'),
  },
  {
    id: 5,
    name: 'Lindy 26',
    brand: 'HERMÈS',
    category: 'bags',
    price: 8150,
    color: 'Craie',
    inStock: true,
    description: 'The versatile Lindy in Clemence leather.',
    image: require('../images/Hermes/lindy.webp'),
  },
  {
    id: 6,
    name: 'Silk Twilly',
    brand: 'HERMÈS',
    category: 'accessories',
    price: 220,
    color: 'Orange',
    inStock: true,
    description: 'Silk twilly to adorn your bag or wrist.',
    image: require('../images/Hermes/twilly.webp'),
  },

  // ============ CHANEL (5 products) ============
  {
    id: 7,
    name: 'Boy Bag Medium',
    brand: 'CHANEL',
    category: 'bags',
    price: 7800,
    color: 'Black',
    inStock: true,
    description: 'The CHANEL Boy with architectural hardware.',
    image: require('../images/Chanel/boybag.webp'),
  },
  {
    id: 8,
    name: '2.55 Reissue',
    brand: 'CHANEL',
    category: 'bags',
    price: 9200,
    color: 'Black',
    inStock: true,
    description: 'The original 2.55 designed by Coco Chanel.',
    image: require('../images/Chanel/chanel25.webp'),
  },
  {
    id: 9,
    name: 'Classic Flap Medium',
    brand: 'CHANEL',
    category: 'bags',
    price: 10800,
    color: 'Black',
    inStock: true,
    description: 'The iconic quilted Classic Flap in lambskin.',
    image: PLACEHOLDER,
  },
  {
    id: 10,
    name: 'Gabrielle Hobo',
    brand: 'CHANEL',
    category: 'bags',
    price: 5200,
    color: 'Beige',
    inStock: true,
    description: 'The Gabrielle hobo with double chain strap.',
    image: PLACEHOLDER,
  },
  {
    id: 11,
    name: 'Deauville Tote',
    brand: 'CHANEL',
    category: 'bags',
    price: 3800,
    color: 'Navy',
    inStock: true,
    description: 'The casual Deauville tote in canvas.',
    image: PLACEHOLDER,
  },

  // ============ DIOR (5 products) ============
  {
    id: 12,
    name: 'Lady Dior Medium',
    brand: 'DIOR',
    category: 'bags',
    price: 6100,
    color: 'Black',
    inStock: true,
    description: 'The iconic Lady Dior in Cannage lambskin.',
    image: require('../images/Dior/dior.webp'),
  },
  {
    id: 13,
    name: 'Saddle Bag',
    brand: 'DIOR',
    category: 'bags',
    price: 4100,
    color: 'Oblique',
    inStock: true,
    description: 'The reinvented Dior Saddle in Oblique jacquard.',
    image: require('../images/Dior/saddle.webp'),
  },
  {
    id: 14,
    name: 'Book Tote Medium',
    brand: 'DIOR',
    category: 'bags',
    price: 3500,
    color: 'Blue Oblique',
    inStock: true,
    description: 'The Dior Book Tote with iconic Oblique motif.',
    image: require('../images/Dior/tote.webp'),
  },
  {
    id: 15,
    name: '30 Montaigne',
    brand: 'DIOR',
    category: 'bags',
    price: 4200,
    color: 'Black',
    inStock: true,
    description: 'The 30 Montaigne with CD clasp.',
    image: PLACEHOLDER,
  },
  {
    id: 16,
    name: 'Bobby Bag',
    brand: 'DIOR',
    category: 'bags',
    price: 3800,
    color: 'Camel',
    inStock: true,
    description: 'The Bobby bag with curved flap.',
    image: PLACEHOLDER,
  },

  // ============ LOUIS VUITTON (5 products) ============
  {
    id: 17,
    name: 'Neverfull MM',
    brand: 'LOUIS VUITTON',
    category: 'bags',
    price: 2030,
    color: 'Monogram',
    inStock: true,
    description: 'The iconic Neverfull in Monogram canvas.',
    image: PLACEHOLDER,
  },
  {
    id: 18,
    name: 'Speedy 25',
    brand: 'LOUIS VUITTON',
    category: 'bags',
    price: 1960,
    color: 'Monogram',
    inStock: true,
    description: 'The timeless Speedy with adjustable strap.',
    image: PLACEHOLDER,
  },
  {
    id: 19,
    name: 'Capucines BB',
    brand: 'LOUIS VUITTON',
    category: 'bags',
    price: 6350,
    color: 'Noir',
    inStock: true,
    description: 'The refined Capucines in Taurillon leather.',
    image: PLACEHOLDER,
  },
  {
    id: 20,
    name: 'Alma BB',
    brand: 'LOUIS VUITTON',
    category: 'bags',
    price: 1850,
    color: 'Monogram',
    inStock: true,
    description: 'The elegant Alma with curved silhouette.',
    image: PLACEHOLDER,
  },
  {
    id: 21,
    name: 'Pochette Métis',
    brand: 'LOUIS VUITTON',
    category: 'bags',
    price: 2570,
    color: 'Monogram',
    inStock: true,
    description: 'The versatile Pochette Métis crossbody.',
    image: PLACEHOLDER,
  },

  // ============ GUCCI (5 products) ============
  {
    id: 22,
    name: 'GG Marmont Small',
    brand: 'GUCCI',
    category: 'bags',
    price: 2890,
    color: 'Black',
    inStock: true,
    description: 'The GG Marmont in matelassé leather.',
    image: PLACEHOLDER,
  },
  {
    id: 23,
    name: 'Jackie 1961',
    brand: 'GUCCI',
    category: 'bags',
    price: 3100,
    color: 'Brown',
    inStock: true,
    description: 'The reimagined Jackie with curved shape.',
    image: PLACEHOLDER,
  },
  {
    id: 24,
    name: 'Dionysus',
    brand: 'GUCCI',
    category: 'bags',
    price: 2980,
    color: 'GG Supreme',
    inStock: true,
    description: 'The Dionysus with tiger head closure.',
    image: PLACEHOLDER,
  },
  {
    id: 25,
    name: 'Horsebit 1955',
    brand: 'GUCCI',
    category: 'bags',
    price: 3200,
    color: 'Brown',
    inStock: true,
    description: 'The Horsebit 1955 shoulder bag.',
    image: PLACEHOLDER,
  },
  {
    id: 26,
    name: 'Bamboo 1947',
    brand: 'GUCCI',
    category: 'bags',
    price: 4500,
    color: 'Cuir',
    inStock: true,
    description: 'The iconic Bamboo handle bag.',
    image: PLACEHOLDER,
  },

  // ============ CARTIER (5 products) ============
  {
    id: 27,
    name: 'Juste un Clou Bracelet',
    brand: 'CARTIER',
    category: 'jewelry',
    price: 8850,
    color: 'Yellow Gold',
    inStock: true,
    description: 'A nail transformed into fine jewelry.',
    image: require('../images/Cartier/juste.webp'),
  },
  {
    id: 28,
    name: 'Love Bracelet',
    brand: 'CARTIER',
    category: 'jewelry',
    price: 7650,
    color: 'Yellow Gold',
    inStock: true,
    description: 'The iconic Love bracelet in 18K gold.',
    image: PLACEHOLDER,
  },
  {
    id: 29,
    name: 'Trinity Ring',
    brand: 'CARTIER',
    category: 'jewelry',
    price: 1580,
    color: 'Tri-Gold',
    inStock: true,
    description: 'Three intertwined bands in yellow, white, and rose gold.',
    image: PLACEHOLDER,
  },
  {
    id: 30,
    name: 'Panthère Ring',
    brand: 'CARTIER',
    category: 'jewelry',
    price: 24500,
    color: 'Yellow Gold',
    inStock: true,
    description: 'The legendary Panthère with emerald eyes.',
    image: PLACEHOLDER,
  },
  {
    id: 31,
    name: 'Love Necklace',
    brand: 'CARTIER',
    category: 'jewelry',
    price: 3450,
    color: 'Rose Gold',
    inStock: true,
    description: 'The Love pendant necklace in 18K gold.',
    image: PLACEHOLDER,
  },

  // ============ ROLEX (5 products) ============
  {
    id: 32,
    name: 'Datejust 36',
    brand: 'ROLEX',
    category: 'watches',
    price: 8550,
    color: 'Silver',
    inStock: true,
    description: 'The classic Datejust with Jubilee bracelet.',
    image: PLACEHOLDER,
  },
  {
    id: 33,
    name: 'Submariner',
    brand: 'ROLEX',
    category: 'watches',
    price: 10250,
    color: 'Black',
    inStock: true,
    description: 'The legendary diving watch.',
    image: PLACEHOLDER,
  },
  {
    id: 34,
    name: 'Day-Date 40',
    brand: 'ROLEX',
    category: 'watches',
    price: 38900,
    color: 'Yellow Gold',
    inStock: true,
    description: 'The President watch in 18K gold.',
    image: PLACEHOLDER,
  },
  {
    id: 35,
    name: 'GMT-Master II',
    brand: 'ROLEX',
    category: 'watches',
    price: 11850,
    color: 'Pepsi',
    inStock: true,
    description: 'The iconic dual-timezone watch.',
    image: PLACEHOLDER,
  },
  {
    id: 36,
    name: 'Explorer I',
    brand: 'ROLEX',
    category: 'watches',
    price: 7650,
    color: 'Black',
    inStock: true,
    description: 'The adventurer\'s watch since 1953.',
    image: PLACEHOLDER,
  },

  // ============ PRADA (5 products) ============
  {
    id: 37,
    name: 'Galleria Saffiano',
    brand: 'PRADA',
    category: 'bags',
    price: 3750,
    color: 'Nero',
    inStock: true,
    description: 'The structured Galleria in Saffiano leather.',
    image: PLACEHOLDER,
  },
  {
    id: 38,
    name: 'Re-Edition 2005',
    brand: 'PRADA',
    category: 'bags',
    price: 1850,
    color: 'Black',
    inStock: true,
    description: 'The cult Re-Edition with detachable pouches.',
    image: PLACEHOLDER,
  },
  {
    id: 39,
    name: 'Cleo Brushed',
    brand: 'PRADA',
    category: 'bags',
    price: 3200,
    color: 'White',
    inStock: true,
    description: 'The sculptural Cleo in brushed leather.',
    image: PLACEHOLDER,
  },
  {
    id: 40,
    name: 'Double Bag',
    brand: 'PRADA',
    category: 'bags',
    price: 3300,
    color: 'Cipria',
    inStock: true,
    description: 'The Double bag in Saffiano leather.',
    image: PLACEHOLDER,
  },
  {
    id: 41,
    name: 'Symbole Bag',
    brand: 'PRADA',
    category: 'bags',
    price: 2800,
    color: 'Black',
    inStock: true,
    description: 'The Symbole with enameled triangle logo.',
    image: PLACEHOLDER,
  },

  // ============ ACCESSORIES - HERMÈS (2 more) ============
  {
    id: 42,
    name: 'Carré 90 Silk Scarf',
    brand: 'HERMÈS',
    category: 'accessories',
    price: 650,
    color: 'Multicolor',
    inStock: true,
    description: 'The iconic Carré in silk twill.',
    image: require('../images/Hermes/carre.webp'),
  },
];

// Brands
export const brands = [
  { id: 'all', name: 'All Brands' },
  { id: 'HERMÈS', name: 'Hermès' },
  { id: 'CHANEL', name: 'Chanel' },
  { id: 'LOUIS VUITTON', name: 'Louis Vuitton' },
  { id: 'DIOR', name: 'Dior' },
  { id: 'GUCCI', name: 'Gucci' },
  { id: 'PRADA', name: 'Prada' },
  { id: 'CARTIER', name: 'Cartier' },
  { id: 'ROLEX', name: 'Rolex' },
];

// Categories (only categories with actual products)
export const categories = [
  { id: 'all', name: 'All', icon: 'grid-outline' },
  { id: 'bags', name: 'Bags', icon: 'bag-outline' },
  { id: 'jewelry', name: 'Jewelry', icon: 'diamond-outline' },
  { id: 'watches', name: 'Watches', icon: 'watch-outline' },
  { id: 'accessories', name: 'Accessories', icon: 'glasses-outline' },
];

// Featured Brands for Home Page
export const featuredBrands = [
  { id: 'HERMÈS', name: 'Hermès', image: require('../images/Hermes/hermes3.webp'), itemCount: 7 },
  { id: 'CHANEL', name: 'Chanel', image: require('../images/Chanel/chanel1.png'), itemCount: 5 },
  { id: 'LOUIS VUITTON', name: 'Louis Vuitton', image: require('../images/LV/LV.jpg'), itemCount: 5 },
  { id: 'DIOR', name: 'Dior', image: require('../images/Dior/dior1.png'), itemCount: 5, imagePosition: 'top' },
  { id: 'GUCCI', name: 'Gucci', image: require('../images/Gucci/Gucci.jpeg'), itemCount: 5 },
  { id: 'CARTIER', name: 'Cartier', image: require('../images/Cartier/cartier1.png'), itemCount: 5 },
  { id: 'ROLEX', name: 'Rolex', image: require('../images/Rolex/Rolex1.jpg'), itemCount: 5, imagePosition: 'top' },
  { id: 'PRADA', name: 'Prada', image: require('../images/Prada/prada-main.jpg'), itemCount: 5 },
];

// For backwards compatibility
export const collections = featuredBrands;

// New Arrivals (first 8 products)
export const newArrivals = products.slice(0, 8);

// AI Recommendations
export const aiRecommendations = [
  {
    id: 1,
    title: 'Perfect Match',
    message: 'Based on your style, the Birkin 25 is perfect for you',
    product: products[0],
  },
  {
    id: 2,
    title: 'Complete Your Look',
    message: 'The Cartier Love Bracelet pairs beautifully',
    product: products[27],
  },
];

// Recently Viewed
export const recentlyViewed = [
  products[0],
  products[6],
  products[11],
  products[26],
];

// Purchase History
export const purchaseHistory = [
  { id: 1, product: products[0], date: '2024-02-15', price: 11400, status: 'delivered' },
  { id: 2, product: products[6], date: '2024-01-28', price: 7800, status: 'delivered' },
];

// Featured Banners
export const banners = [
  {
    id: 1,
    title: 'Hermès Icons',
    subtitle: 'Birkin, Kelly & Constance',
    image: require('../images/Hermes/birkin.webp'),
    color: '#FF6B35',
  },
  {
    id: 2,
    title: 'Fine Jewelry',
    subtitle: 'Cartier Collection',
    image: require('../images/Cartier/juste.webp'),
    color: '#C9A962',
  },
];

// Price Ranges
export const priceRanges = [
  { id: 'all', name: 'All Prices', min: 0, max: Infinity },
  { id: 'under5k', name: 'Under $5,000', min: 0, max: 5000 },
  { id: '5k-10k', name: '$5,000 - $10,000', min: 5000, max: 10000 },
  { id: 'over10k', name: 'Over $10,000', min: 10000, max: Infinity },
];

// Advisor Appointments
export const advisorAppointments = [
  {
    id: 1,
    date: 'Today',
    time: '2:00 PM',
    duration: '1 hour',
    customer: 'Alexandra Chen',
    avatar: 'AC',
    type: 'Private Shopping',
    notes: 'Interested in Hermès Birkin',
    interests: ['Hermès', 'Bags', 'Limited Edition'],
    aiInsight: 'Alexandra has viewed Birkin 25 Orange 5 times this week. She prefers gold hardware and has a 92% purchase conversion rate for items she views more than 3 times.',
  },
  {
    id: 2,
    date: 'Today',
    time: '4:30 PM',
    duration: '45 min',
    customer: 'Victoria Sterling',
    avatar: 'VS',
    type: 'Watch Consultation',
    notes: 'Looking for Rolex Datejust',
    interests: ['Rolex', 'Watches', 'Gold'],
    aiInsight: 'Victoria recently searched for "Rolex Datejust 36mm" and compared prices. She typically makes purchases within 2 weeks of initial consultation.',
  },
  {
    id: 3,
    date: 'Tomorrow',
    time: '11:00 AM',
    duration: '1.5 hours',
    customer: 'Sophia Laurent',
    avatar: 'SL',
    type: 'Jewelry Viewing',
    notes: 'VIP appointment - Met Gala preparation',
    interests: ['Cartier', 'Diamonds', 'Statement Pieces'],
    aiInsight: 'Sophia is attending the Met Gala and needs statement jewelry. She has a history of purchasing high-value items for events. Budget estimated at $50,000+.',
  },
  {
    id: 4,
    date: 'Mar 6',
    time: '3:00 PM',
    duration: '1 hour',
    customer: 'Emma Rothschild',
    avatar: 'ER',
    type: 'Birthday Gift Selection',
    notes: 'Shopping for birthday - loves burgundy',
    interests: ['Evening Wear', 'Accessories', 'Gift Wrapping'],
    aiInsight: 'Emma is shopping for herself. Birthday in 2 weeks. Previous purchases include silk evening wear. Consider burgundy Hermès scarf or Chanel clutch.',
  },
];
